package com.redhack.documentcontrolsystem;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InvoiceDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("invoiceNumber")
	private java.lang.String invoiceNumber;
	@org.kie.api.definition.type.Label("sysWFId")
	private java.lang.String sysWFId;

	private java.math.BigDecimal totalAmt;

	public InvoiceDetails() {
	}

	public java.lang.String getInvoiceNumber() {
		return this.invoiceNumber;
	}

	public void setInvoiceNumber(java.lang.String invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}

	public java.lang.String getSysWFId() {
		return this.sysWFId;
	}

	public void setSysWFId(java.lang.String sysWFId) {
		this.sysWFId = sysWFId;
	}

	public java.math.BigDecimal getTotalAmt() {
		return this.totalAmt;
	}

	public void setTotalAmt(java.math.BigDecimal totalAmt) {
		this.totalAmt = totalAmt;
	}

	public InvoiceDetails(java.lang.String invoiceNumber,
			java.lang.String sysWFId, java.math.BigDecimal totalAmt) {
		this.invoiceNumber = invoiceNumber;
		this.sysWFId = sysWFId;
		this.totalAmt = totalAmt;
	}

}